### ISSUE TITLE
解析失败……

### ISSUE THREAD

**Issue by SoberChina** [vancefantasy/flyer-maker#2]
昨天大概看了一下代码，今天想试一下，发现有几个问题:

1. db 的save 方法是否有必要留着？useGeneratedKeys=true 对于没有主键的或者是主键id是非自增长的uuid结果就不好使了。

2. ` field.getTname().equals("id") || field.getExtra().equalsIgnoreCase("auto_increment")` 判断主键有点不合适吧。
当然 第2个问题解决好了的话，db 的save 方法可以搞成可控制的吗？

**Comment by vancefantasy** [comment]
@SoberChina 
自增主键这里的处理确实不太满意，已在文档中表明 这里的使用限制。

其他人是否有更好的想法？

**Comment by SoberChina** [comment]
先忙工作，有问题我再提issues
