### ISSUE TITLE
flyermaker 命令找不到  win10

### ISSUE THREAD

**Issue by tian1iang** [vancefantasy/flyer-maker#4]
flyermaker 命令找不到  win10

**Comment by vancefantasy** [comment]
@AndyTian Sorry，[v0.0.1](https://github.com/vancefantasy/flyer-maker/releases/tag/v0.0.1)软件包，不兼容Windows，这里给出Windows的短暂使用方案。

方案一，clone代码到本地，导入IDE工具（例：IntelliJ IDEA），以main函数运行（配置文件会使用工程中的配置）

方案二，clone代码到本地，打成jar包使用

    java -Dcli=true -jar flyer-maker.jar -h //帮助
    java -Dcli=true -jar flyer-maker.jar -v //版本信息
    java -Dcli=true -jar flyer-maker.jar -f application.properties //根据指定配置生成工程

谢谢使用！
